let shop = [
  {
    category: "Mens",
    items: [
      {
        type: "Tops",
        classification: [
          {
            id: 0,

            brand: "Dior",
            color: "Blue",
            size: "Small, Medium, Large",
            price: "₱999.00",
            image: "img/men_tops/top_1_front.png",
            description: "Comfortable and stylish top with ...",
          },
          {
            id: 1,

            brand: "Adidas",
            color: "Khaki Brown",
            size: "Small, Medium, Large",
            price: "₱449.99",
            image: "img/men_tops/top_2_front.png",
            description: " Crafted with quality and comfort in ...",
          },
          {
            id: 2,

            brand: "Nike",
            color: "Dirty White",
            size: "Small, Medium, Large",
            price: "₱399.99",
            image: "img/men_tops/top_3_front.png",
            description: "Breathable Puma men's top suitable...",
          },
          {
            id: 3,

            brand: "Dickies",
            color: "White and Pink",
            size: "Small, Medium, Large",
            price: "₱549.99",
            image: "img/men_tops/top_4_front.png",
            description: "Whether you're aiming for a ...",
          },
          {
            id: 4,

            brand: "Reebok",
            color: "Black, Brown, White ",
            size: "Medium, Large, XL",
            price: "₱479.99",
            image: "img/men_tops/top_5_front.png",
            description: "Classic Reebok men's top with a ...",
          },
        ],
      },
      {
        type: "Pants",
        classification: [
          {
            id: 0,

            brand: "Lee",
            color: "White",
            size: "Small, Medium, Large",
            price: "₱249.99",
            image: "img/men_bottom/bottom_1_front.png",
            description: "Comfortable but stylish mens shorts.",
          },
          {
            id: 1,

            brand: "Nike",
            color: "Black and Brown",
            size: "Medium, Large, XL",
            price: "₱399.99",
            image: "img/men_bottom/bottom_2_front.png",
            description: "Crafted for those who demand both ...",
          },
          {
            id: 2,

            brand: "Puma",
            color: "White",
            size: "Small, Large, XL",
            price: "₱369.99",
            image: "img/men_bottom/bottom_3_front.png",
            description: "White pants with 6 pockets.",
          },
          {
            id: 3,

            brand: "Under Armour",
            color: "Gray Heather",
            size: "Small, Medium, Large",
            price: "₱749.99",
            image: "img/men_bottom/bottom_4_front.png",
            description: "High-performance Under Armour ...",
          },

          {
            id: 4,

            brand: "Under Armour",
            color: "Brown",
            size: "Small, Medium, Large",
            price: "₱729.99",
            image: "img/men_bottom/bottom_5_front.png",
            description: "Leather jogger pants with 6 pockets.",
          },
        ],
      },
      {
        type: "Sweater",
        classification: [
          {
            id: 0,

            brand: "Nike",
            color: "Brown",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/men_sweater/sweater_1_front.png",
            description: "A stylish sweater with a comfortable...",
          },
          {
            id: 1,
            brand: "Lacoste",
            color: "Brown",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/men_sweater/sweater_2_front.png",
            description: "A printed cotton sweater.",
          },
          {
            id: 2,

            brand: "Adidas",
            color: "Green",
            size: "Small, Medium, Large",
            price: "₱589.99",
            image: "img/men_sweater/sweater_3_front.png",
            description: " A perfect fusion of style and ... ",
          },
          {
            id: 3,

            brand: "Nike",
            color: "White",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/men_sweater/sweater_4_front.png",
            description: "A timeless addition to your cold-...",
          },
          {
            id: 4,

            brand: "Nike",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/men_sweater/sweater_5_front.png",
            description: "The perfect blend of comfort and ...",
          },
        ],
      },
      {
        type: "Co-ords",
        classification: [
          {
            id: 0,
            brand: "H&M",
            color: "White & Blue",
            size: "Small, Medium, Large",
            price: "₱799.99",
            image: "img/men_co-ords/co-ords_1_front.png",
            description: "This set includes a pair of stylish ...",
          },
          {
            id: 1,
            brand: "Lee",
            color: "Black & Brown",
            size: "Small, Medium, Large",
            price: "₱699.99",
            image: "img/men_co-ords/co-ords_2_front.png",
            description: "This pair features a classic t-shirt ...",
          },
          {
            id: 2,
            brand: "Penshoppe",
            color: "Black and Cream",
            size: "Small, Medium, Large",
            price: "₱799.99",
            image: "img/men_co-ords/co-ords_3_front.png",
            description: " This set includes uniquely designed ...",
          },
          {
            id: 3,
            brand: "Uniqlo",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱999.99",
            image: "img/men_co-ords/co-ords_4_front.png",
            description: "Crafted from high-quality materials, ...",
          },
          {
            id: 4,
            brand: "Zalora",
            color: "Black and White",
            size: "Small, Medium, Large",
            price: "₱959.99",
            image: "img/men_co-ords/co-ords_5_front.png",
            description: "A perfect fusion of athletic flair and ... ",
          },
        ],
      },
    ],
  },
  {
    category: "Women",
    items: [
      {
        type: "Tops",
        classification: [
          {
            id: 0,
            brand: "Chanel",
            color: "Cornflower Blue",
            size: "Small, Medium, Large",
            price: "₱1,599.00",
            image: "img/women_tops/tops_1_front.png",
            description: "Floral crop top with puff sleaves.",
          },
          {
            id: 1,
            brand: "Dior",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱1,499.00",
            image: "img/women_tops/tops_2_front.png",
            description: "Big Bow Back Ruffle Hem Cami Top.",
          },
          {
            id: 2,
            brand: "Zara",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱999.00",
            image: "img/women_tops/tops_3_front.png",
            description: "Long sleeve crop top.",
          },
          {
            id: 3,
            brand: "Zaful",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱999.00",
            image: "img/women_tops/tops_4_front.png",
            description: " A perfect blend of fashion and ...",
          },
          {
            id: 4,
            brand: "Zalora",
            color: "Navy Blue",
            size: "Small, Medium, Large",
            price: "₱899.00",
            image: "img/women_tops/tops_2_front.png",
            description: "The deep navy blue color offers a ...",
          },
        ],
      },
      {
        type: "Pants",
        classification: [
          {
            id: 0,
            brand: "Zalora",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱899.00",
            image: "img/women_bottom/bottom_3_front.png",
            description: "Balck offive pants.",
          },
        ],
      },
      {
        type: "Skirt",
        classification: [
          {
            id: 0,
            brand: "H&M",
            color: "Pearl white",
            size: "Small, Medium, Large",
            price: "₱799.00",
            image: "img/women_bottom/bottom_1_front.png",
            description: "This skirt is designed to perfectly ...",
          },
          {
            id: 1,
            brand: "Uniqlo",
            color: "Peach",
            size: "Small, Medium, Large",
            price: "₱699.00",
            image: "img/women_bottom/bottom-2_front.png",
            description: "Flowery pattern skirt ...",
          },
          {
            id: 2,
            brand: "Penshoppe",
            color: "White",
            size: "Small, Medium, Large",
            price: "₱1,099.00",
            image: "img/women_bottom/bottom_5_front.png",
            description: "White skirt with ribbon .",
          },
          {
            id: 3,
            brand: "Geuss",
            color: "Cream",
            size: "Small, Medium, Large",
            price: "₱849.00",
            image: "img/women_bottom/bottom_4_front.png",
            description: "Fitted short skirt with slit ...",
          },
        ],
      },
      {
        type: "Dress",
        classification: [
          {
            id: 0,
            brand: "Shein",
            color: "Baby Blue",
            size: "Small, Medium, Large",
            price: "₱799.99",
            image: "img/women_dress/blue_short_dress_front.png",
            description: "Jacquard Square Neck Puff ...",
          },
          {
            id: 1,
            brand: "Zalora",
            color: "Olive Green",
            size: "Small, Medium, Large",
            price: "₱899.99",
            image: "img/women_dress/long_dress_green_front.png",
            description: "Solid Tie Shoulder Cami ..",
          },
          {
            id: 2,
            brand: "Zaful",
            color: "Salmon Pink",
            size: "Small, Medium, Large",
            price: "₱899.99",
            image: "img/women_dress/pink_dress_front.png",
            description: " Floral Print Cami Dress ...",
          },
          {
            id: 3,
            brand: "Penshoppe",
            color: "Carnation Pink",
            size: "Small, Medium, Large",
            price: "₱799.99",
            image: "img/women_dress/pink_floral_dress_front.png",
            description: "Allover Floral Print Ruched Bust ...",
          },
          {
            id: 4,
            brand: "Zalora",
            color: "Silver",
            size: "Small, Medium, Large",
            price: "₱799.99",
            image: "img/women_dress/sexy_grey_dress_front.png",
            description: " Crisscross Backless Ruched ...",
          },
        ],
      },
      {
        type: "Co-ords",
        classification: [
          {
            id: 0,
            brand: "Zalora",
            color: "White",
            size: "Small, Medium, Large",
            price: "₱1,099.00",
            image: "img/women_co-ords/co-ords_1_front.png",
            description: "Contrast Trim Bow Front Crop ...",
          },
          {
            id: 1,
            brand: "Zara",
            color: "White and Green",
            size: "Small, Medium, Large",
            price: "₱999.99",
            image: "img/women_co-ords/co-ords_2_front.png",
            description: " Solid Crop Top & Ditsy ...",
          },
          {
            id: 2,
            brand: "H&M",
            color: "Peral White",
            size: "Small, Medium, Large",
            price: "₱1,099.99",
            image: "img/women_co-ords/co-ords_3_front.png",
            description: "Ladies' Lace Camisole Top And Mermaid Hem ...",
          },
          {
            id: 3,
            brand: "Penshoppe",
            color: "Almond",
            size: "Small, Medium, Large",
            price: "₱899.99",
            image: "img/women_co-ords/co-ords_4_front.png",
            description: "Knitted Diamond Checkered Printed ...",
          },
          {
            id: 4,
            brand: "Bench",
            color: "Onyx Black",
            size: "Small, Medium, Large",
            price: "₱999.99",
            image: "img/women_co-ords/co-ords_5_front.png",
            description: " Ladies' Solid Color Faux Leather ...",
          },
        ],
      },
    ],
  },
  {
    category: "Kids",
    items: [
      {
        type: "Tops",
        classification: [
          {
            id: 0,
            brand: "Bench",
            color: "White and Black",
            size: "Small, Medium, Large",
            price: "₱399.99",
            image: "img/kids_tops/top_1_front.png",
            description: "inside shirt white and...",
          },
          {
            id: 1,
            brand: "H&M",
            color: "White",
            size: "Small, Medium, Large",
            price: "₱499.99",
            image: "img/kids_tops/top_2_front.png",
            description: "Crop top polo ",
          },
          {
            id: 2,
            brand: "Hello Kitty",
            color: "White, Gray and Black",
            size: "Small, Medium, Large",
            price: "₱399.99",
            image: "img/kids_tops/top_3_front.png",
            description: ".Letter Graphic Tee",
          },
          {
            id: 3,
            brand: "Hello Kitty",
            color: "Baby Powder White",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/kids_tops/top_4_front.png",
            description: "Knitted Solid Off Shoulder ...",
          },
          {
            id: 4,
            brand: "Old Navy",
            color: "Pink",
            size: "Small, Medium, Large",
            price: "₱399.99",
            image: "img/kids_tops/top_5_front.png",
            description: "Maong shorts with pink heart tshirt. ",
          },
        ],
      },
      {
        type: "Pants",
        classification: [
          {
            id: 0,
            brand: "Old Navy",
            color: "Copper Brown",
            size: "Small, Medium, Large",
            price: "₱499.99",
            image: "img/kids_bottom/bottom_4_front.png",
            description: "Straight leg pants.",
          },
          {
            id: 1,
            brand: "H&M",
            color: "Camel Brown",
            size: "Small, Medium, Large",
            price: "₱459.99",
            image: "img/kids_bottom/bottom_5_front.png",
            description: "Jogger pants with six pockets.",
          },
        ],
      },
      {
        type: "Shorts",
        classification: [
          {
            id: 0,
            brand: "Penshoppe",
            color: "Baby Blue",
            size: "Small, Medium, Large",
            price: "₱499.99",
            image: "img/kids_bottom/bottom_1_front.png",
            description: "Striped Print Bow Front ...",
          },
          {
            id: 2,
            brand: "Old Navy",
            color: "Copper Brown",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/kids_bottom/bottom_2_front.png",
            description: "Fashionable And Elegant Plaid Woven Shorts ...",
          },
          {
            id: 3,
            brand: "Zara",
            color: "Midnight Black",
            size: "Small, Medium, Large",
            price: "₱499.99",
            image: "img/kids_bottom/bottom_3_front.png",
            description: "Solid Color Paper Bag Tie Waist Bowknot ...",
          },
        ],
      },
      {
        type: "Dress",
        classification: [
          {
            id: 0,
            brand: "Penshoppe",
            color: "Navy Blue",
            size: "Small, Medium, Large",
            price: "₱699.00",
            image: "img/kids_dress/dress_1_front.png",
            description: "Preppy-Style Heart-Shaped Printed ...",
          },
          {
            id: 1,
            brand: "Bench",
            color: "Navy Blue",
            size: "Small, Medium, Large",
            price: "₱659.00",
            image: "img/kids_dress/dress_2_front.png",
            description: "Unleash the trendsetter in your ...",
          },
          {
            id: 2,
            brand: "Shein",
            color: "Cedar Brown",
            size: "Small, Medium, Large",
            price: "₱699.00",
            image: "img/kids_dress/dress_3_front.png",
            description: "Embrace elegance with Shein's Cedar ...",
          },
          {
            id: 3,
            brand: "Zara",
            color: "Periwinkle Purple",
            size: "Small, Medium, Large",
            price: "₱599.00",
            image: "img/kids_dress/dress_4_front.png",
            description: "Everyday Casual Knitted Solid Color..",
          },
          {
            id: 4,
            brand: "H&M",
            color: "Brink Pink",
            size: "Small, Medium, Large",
            price: "₱599.00",
            image: "img/kids_dress/dress_5_front.png",
            description: "Double-Layered Floral Printed Party ...",
          },
        ],
      },
      {
        type: "Co-ords",
        classification: [
          {
            id: 0,
            brand: "Shein",
            color: "Taupe Brown",
            size: "Small, Medium, Large",
            price: "₱799.00",
            image: "img/kids_co-ords/co-ords_1_front.png",
            description: "Letter Graphic Striped Trim Sweater & ...",
          },
          {
            id: 1,
            brand: "Zalora",
            color: "Navy Blue",
            size: "Small, Medium, Large",
            price: "₱899.00",
            image: "img/kids_co-ords/co-ords_2_front.png",
            description: "Flower Decorated Knitted Cardigan...",
          },
          {
            id: 2,
            brand: "Zara",
            color: "Camel Brown, Black",
            size: "Small, Medium, Large",
            price: "₱799.00",
            image: "img/kids_co-ords/co-ord_3_front.png",
            description: "Ruffle Trim Cable Knit Cardigan...",
          },
          {
            id: 3,
            brand: "Old Navy",
            color: "Ginger Brown",
            size: "Small, Medium, Large",
            price: "₱799.00",
            image: "img/kids_co-ords/co-ords_4_front.png",
            description: "Knitted kids beach wear.",
          },
          {
            id: 4,
            brand: "Zara",
            color: "Dark Brown",
            size: "Small, Medium, Large",
            price: "₱599.00",
            image: "img/kids_co-ords/co-ords_5_front.png",
            description: "Checkered sweater set",
          },
        ],
      },
    ],
  },
];

module.exports = { shop };
